project_id = "otpbnwpnprgdncexvksx"

[functions.create-user]
verify_jwt = false

[functions.whatsapp-verify]
verify_jwt = false

[functions.whatsapp-instance]
verify_jwt = false

[functions.zapsign-enviar]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false